//
//  TermsOfUse.swift
//  team-10-c3
//
//  Created by Huy Tran on 10/06/26.
//

import SwiftUI

struct TermsOfUse: View {
    
    var body: some View {
        ScrollView {
            VStack(spacing: 15) {
                Introduction
                
                ForEach(getTerms()) { policy in
                    buildTerm(policy: policy)
                }
            }
            .padding(.horizontal, 30)
        }
        .foregroundStyle(.textPrimary)
        .toolbar {
            ToolbarItem(placement: .principal) {
                Text("Terms of Use")
                    .font(.system(size: 28, weight: .semibold))
            }
        }
        .navigationBarTitleDisplayMode(.inline)
    }
}

private var Introduction: some View {
    VStack {
        // title
        VStack(alignment: .leading) {
            Text("Kiddly Terms of Use")
                .foregroundStyle(.textPrimary)
                .font(.system(size: 20, weight: .semibold))
                .frame(maxWidth: .infinity, alignment: .leading)
            Text("Last updated: June 2026")
                .foregroundStyle(.textSecondary)
                .font(.system(size: 14, weight: .semibold))
                .italic(true)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(.horizontal, 10)
        
        // description
        Text("Use Kiddly as it is intended — to support your family. Do not misuse it, do not use it to harm anyone, and understand that we provide guidance content in good faith but it is NOT a substitute for professional advice."
        )
        .font(.system(size: 15, weight: .regular))
            .padding(.top, 10)
    }
}

private func getTerms() -> [Policy] {
    [
        Policy(
            title: "1. Who can use Kiddly",
            lines: [
                "Kiddly is intended for use by parents and guardians aged 18 and above. By downloading and using Kiddly you confirm that:",
                "",
                "• You are 18 years of age or older",
                "• You are the parent or legal guardian of the child whose profile you create in the app",
                "• You are using the app on a device you own or have permission to use",
                "• You will use the app in compliance with the laws of your country"
            ]
        ),

        Policy(
            title: "2. What Kiddly is",
            lines: [
                "Kiddly is a family screen time guidance app. It helps parents understand their child's digital habits through AI-generated daily and weekly summaries, receive one weekly suggested activity or conversation prompt personalised to their child's usage patterns, track whether they tried the suggestion and how their child responded, and access a library of static offline activities to do together as a family.",
                "",
                "The daily and weekly summaries, weekly suggestions, and conversation prompts in Kiddly are generated by AI based on your child's screen time and content data. They are general guidance content intended to support family connection — they are not medical advice, psychological advice, or professional parenting advice. AI-generated content may occasionally be inaccurate or not perfectly suited to your child's specific situation. Use your own judgment as a parent when acting on any suggestion.",
                "",
                "The offline activity library contains static content — activity guides, game instructions, and tips — written and curated by the Kiddly team. This content is provided for general family guidance purposes. We make reasonable efforts to ensure it is accurate, age-appropriate, and safe. However you know your child best — use your judgment when trying any suggested activity."
            ]
        ),

        Policy(
            title: "3. What Kiddly is not",
            lines: [
                "• Kiddly is not a surveillance tool — it is designed to help parents guide their children, not to monitor or control them without their knowledge",
                "• Kiddly is not a child safety guarantee — while session tracking helps parents understand screen habits, we cannot guarantee that all content your child encounters will be appropriate",
                "• Kiddly is not a substitute for direct parent-child communication — the app is designed to support and spark conversation, not replace it",
                "• Kiddly is not a professional parenting, medical, or psychological service — if you have concerns about your child's wellbeing or development, please consult a qualified professional"
            ]
        ),

        Policy(
            title: "4. Your responsibilities as a parent user",
            lines: [
                "By using Kiddly you agree to:",
                "",
                "• Use the app only for its intended purpose of family screen time guidance and connection",
                "• Not use the app to surveil, control, or harm any person",
                "• Inform your child in an age-appropriate way that screen activity during Kiddly sessions may be analysed — transparency with your child is both a legal requirement in many jurisdictions and the right thing to do",
                "• Supervise your child during any physical activity suggested by the app — Kiddly is not responsible for injuries or harm resulting from attempted activities",
                "• Not attempt to reverse engineer, modify, or misuse the app or its content"
            ]
        ),

        Policy(
            title: "5. Screen recording consent",
            lines: [
                "When you enable screen recording in Kiddly:",
                "",
                "• You confirm that you are the owner or primary user of the device",
                "• You confirm that your child will be using the device during the recorded session",
                "• You confirm that you understand what is recorded and how it is processed as described in our Privacy Policy",
                "• You are responsible for ensuring that screen recording is used in compliance with the laws of your country",
                "• You understand that screen recording must be actively started by you before each session — it does not run in the background without your knowledge"
            ]
        ),

        Policy(
            title: "6. AI-generated content",
            lines: [
                "Kiddly uses artificial intelligence to generate daily summaries, weekly summaries, and weekly suggestions based on your child's screen time and content data. By using these features you acknowledge that:",
                "",
                "• AI-generated content is based on usage patterns and may not perfectly reflect your child's individual circumstances",
                "• Suggestions are starting points for family connection — not instructions that must be followed",
                "• You retain full parental judgment and discretion over whether to act on any AI-generated suggestion",
                "• Kiddly is not liable for outcomes resulting from acting on AI-generated suggestions"
            ]
        ),

        Policy(
            title: "7. Offline activity library",
            lines: [
                "The offline activity library is static content provided within the app for general family guidance. By using the activity library you acknowledge that:",
                "",
                "• All physical activities should be supervised by a parent or guardian at all times",
                "• Age recommendations on each activity card are guidelines — you know your child's abilities and readiness best",
                "• Kiddly is not liable for any injury, harm, or damage resulting from attempted activities"
            ]
        ),

        Policy(
            title: "8. History feature",
            lines: [
                "The history feature records your child’s screen time & check-in responses — whether you tried a weekly suggestion and how your child responded. This data is stored on your device and is visible only to you.",
                "",
                "You can delete individual entries or your entire history at any time from Settings."
            ]
        ),

        Policy(
            title: "9. Intellectual property",
            lines: [
                "All content in Kiddly — including activity guides, illustrations, copy, AI prompts, and the app design — is the property of Kiddly and may not be reproduced, distributed, or used commercially without our written permission.",
                "",
                "You may share individual activity tips with other parents for personal, non-commercial use."
            ]
        ),

        Policy(
            title: "10. Limitation of liability",
            lines: [
                "Kiddly is provided as-is. To the fullest extent permitted by law, we are not liable for:",
                "",
                "• Any injury or harm resulting from a suggested activity — all physical activities must be supervised by a parent or guardian",
                "• Any content your child accesses outside of a Kiddly session",
                "• Any inaccuracy in AI-generated summaries or suggestions",
                "• Any loss of data resulting from device failure or accidental deletion",
                "• Any indirect or consequential damages arising from your use of the app"
            ]
        ),

        Policy(
            title: "11. Termination",
            lines: [
                "We reserve the right to suspend or terminate your access to Kiddly if you violate these terms.",
                "",
                "You may delete your account at any time from Settings → Privacy → Delete account."
            ]
        ),

        Policy(
            title: "12. Changes to these terms",
            lines: [
                "We may update these terms from time to time.",
                "",
                "We will notify you through the app before significant changes take effect.",
                "Continued use of Kiddly after that date means you accept the updated terms."
            ]
        )
    ]
}

@ViewBuilder
private func buildTerm (policy: Policy) -> some View {
    VStack(alignment: .leading) {
        Text(policy.title)
            .font(.system(size: 20, weight: .semibold))
            .foregroundStyle(.textPrimary)
        
        VStack(alignment: .leading) {
            ForEach(policy.lines, id: \.self) { line in
                Text(line)
                    .foregroundStyle(.gray)
            }
        }
        .padding(.top, 10)
    }
}

#Preview {
    NavigationStack {
        TermsOfUse()
    }
}
